directories:
  output: dist_electron
  buildResources: build
appId: com.example.starapp
productName: Star App
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - package.json
      - main.js
      - preload.js
win:
  target: nsis
electronVersion: 31.7.7
